version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "petbot"
      POSTGRES_USER: "petbotadmin"
      POSTGRES_PASSWORD: "petbotpassword"
    ports:
      - "5433:5432"
