version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .nest/postgres/:/var/lib/postgresql/data/
    env_file:
      - .test.env
